version: '3'
services:
  src:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: yarn run dev
    expose:
      - "3000"
    ports:
      - 3000:3000
    volumes:
      - ./:/src:cached
    tty: true
    stdin_open: true
